name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.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 }}

          # Options
          user: AbakNacchan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_forks: yes            